sonar.organization=adrigongv23
sonar.projectKey=adrigongv23_G26_Telemetria_TFG
sonar.sources=Plataform_Web
sonar.exclusions=**/migrations/**,**/venv/**,**/static/**,**/media/**
sonar.python.version=3
