# Generated by Django 6.0.2 on 2026-02-19 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temporadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Test')),
                ('descripcion', models.TextField(verbose_name='Objetivo / Descripción del test')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('categoria', models.CharField(choices=[('aerodinamica', 'Aerodinámica'), ('chasis', 'Chasis'), ('business', 'Business & Operations'), ('epowertrain', 'E-Powertrain'), ('electronica', 'Electrónica'), ('sdf', 'SDF'), ('motor_transmision', 'Motor & Transmisión'), ('general', 'General')], default='general', max_length=30)),
                ('resultados', models.TextField(blank=True, null=True, verbose_name='Conclusiones y Resultados')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporadas.temporada')),
            ],
            options={
                'verbose_name': 'Test General',
                'verbose_name_plural': 'Tests Generales',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
