# Generated by Django 6.0.2 on 2026-08-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_patrocinador_contacto_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('aerodinamica', 'Aerodinámica'), ('chasis', 'Chasis'), ('business_operations', 'Business & Operations'), ('epowertrain', 'E-Powertrain'), ('electronica', 'Electrónica'), ('sdf', 'SDF'), ('motor_transmision', 'Motor & Transmisión'), ('software', 'Software'), ('general', 'General')], max_length=30, verbose_name='Área del gasto'),
        ),
    ]
